export const projectList = [
  {
    tag: "Solo Project",
    title: "Sunny Side Up",
    image: [require("../img/sunnysideup.png")],
    link: "https://iym1511.github.io/Sunny-SideUp-PJ/",
    repositories: "https://github.com/iym1511/Sunny-SideUp-PJ",
    introduce1: "이 프로젝트의 이름은 'Sunny-Side-Up'입니다. 계란 후라이의 모습이 태양을 닮아 이렇게 명명하게 되었습니다.",
    introduce2: "GPS 위치를 기반으로 현재 지역의 날씨 정보를 보여주는 기능을 제공합니다. 또한, 5일 후까지의 날씨 예보와 그 기간 동안의 다른 지역들의 날씨를 비교할 수 있는 기능을 포함하고 있습니다.",
    introduce3: "사용자의 가시성을 중요시하여 앱 배경을 실시간 날씨에 맞는 애니메이션으로 구성하였고, 요청 즉시 1차 렌더링을 함으로써 연동하는 API가 응답이 늦어지거나 응답이 없을 경우에도 영향을 최소화 시킬 수 있어서 사용자 경험 측면에서 유리하여 redux-thunk를 사용하게 되었습니다.",
    review : "API를 활용하는 프로젝트를 진행하면서 비동기 작업을 위해 redux-thunk 미들웨어를 도입했습니다. 하지만 미들웨어라는 개념에 익숙하지 않아 처음에는 적용하는 데 어려움을 겪었습니다",
    review2 : "redux-thunk 사용을 목표로 프로젝트에 통합했으나, 초기 단계에서는 이해와 적용이 다소 미숙했던 점이 아쉬웠습니다. 그럼에도 불구하고, 앞으로 이를 지속적으로 다루며 경험을 쌓아가면 이해도가 크게 향상될 것이라 기대합니다.",
    function: "실시간 위치기반 날씨, 5일치 전국 날씨, 날씨에 따른 애니메이션 배경",
    techstack: "React, TypeScript, redux-thunk, style-component",
  },
  {
    tag: "Solo Project",
    title: "Tommorrow World",
    image: [require("../img/tommorrowworld.png")],
    link: "https://iym1511.github.io/Shopping-Project/",
    repositories: "https://github.com/iym1511/Shopping-Project",
    introduce1: "'Tommorrow World' 는 React와 Javascript를 기반으로 한 의류 쇼핑몰 프로젝트 입니다. ",
    introduce2: "회원가입, 로그인, 장바구니, 별점 리뷰 작성과 같은 유저 데이터 관리를 위해 Redux-Toolkit과 Redux-Persist를 사용하였습니다.",
    introduce3: "Redux-Toolkit은 Redux의 강력한 상태 관리 기능을 보다 간결하게 사용할 수 있게 해주며, Redux-Persist는 브라우저 새로고침 시에도 사용자 상태를 유지하도록 도와주어 사용자 경험을 크게 향상시킵니다.",
    review : "프로젝트를 진행하면서 Props 드릴링을 경험하였습니다. 이 과정에서 전역 상태 관리의 중요성에 대해 심도 깊게 고민하게 되었습니다. Redux-Toolkit을 활용하여 학습한 기술 스택을 실제 프로젝트에 적용하며 다양한 문제를 직접 해결하는 과정은 매우 의미 있는 경험이었습니다. ",
    review2 : "더불어, Redux-Toolkit에 그치지 않고 Recoil과 같은 다른 전역 상태 관리 라이브러리에 대한 연구도 확장하였습니다. 이를 통해 문제 해결 능력과 기술적 성장을 도모할 수 있었습니다.",
    function: "회원별 개인 장바구니, 별점 리뷰, 팝업 광고Modal, 회원정보 수정",
    techstack: "React, redux-toolkit, redux-parsist, style-component",
  },
  {
    tag: "Team Project",
    title: "Today Design",
    image: [require("../img/todaydesign.png")],
    link: "https://sjerry-kim.github.io/Portfolio_teamC/",
    repositories: "https://github.com/iym1511/-Project-teamC/tree/master/test-project",
    introduce1: "프론트엔드 공부를 시작하고 처음으로 진행해본 팀 프로젝트 인테리어 업체 비교&견적 사이트 'Today Design' 입니다.",
    introduce2: "팀 내에서 전체적인 디자인구성 + 포토,일러 로고를 제작하였으며 간편 견적페이지 결과도출과 firebase 로그인,회원가입,구글로그인,사용자 정보저장 그리고 DataContext 관리를 맡았습니다.",
    introduce3: "modal 라이브러리인 SweetAlert와 라우터 간 애니메이션인 framer-motion을 사용하여 웹 사이트의 동적인 효과에도 기여하였습니다.",
    review : "팀 프로젝트를 진행하면서 하나의 프로젝트를 완성하기 위해 얼마나 많은 소통이 필요한지 깨달았습니다. 의사소통 조율의 어려움을 극복하고, 역량이 부족한 팀원들에게 도움을 제공하는 과정은 팀으로서 하나의 목표를 향해 나아가는 데 매우 의미 있고 보람찬 경험이었습니다.",
    review2 : "이를 통해 팀원 간의 협력을 강화하고 함께 성장하는 기회를 얻었습니다.",
    function: "유저선택에 따른 업체 추천, 구글 로그인",
    techstack: "React, useContext, firebase",
  },
];
