export const projectList = [
  {
    tag: "Solo Project",
    title: "Tommorrow World",
    image: [require("../img/tommorrowworld.png")],
    link: "https://iym1511.github.io/Shopping-Project/",
    repositories: "https://github.com/iym1511/Shopping-Project",
    introduce: "",
    function: "",
    techstack: "React, redux-toolkit, redux-parsist, style-component",
  },
  {
    tag: "Team Project",
    title: "Today Design",
    image: [require("../img/todaydesign.png")],
    link: "https://sjerry-kim.github.io/Portfolio_teamC/",
    repositories: "https://github.com/iym1511/-Project-teamC/tree/master/test-project",
    introduce: "",
    function: "",
    techstack: "React, useContext, firebase",
  },
  {
    tag: "Solo Project",
    title: "Sunny Side Up",
    image: [require("../img/sunnysideup.png")],
    link: "https://iym1511.github.io/Sunny-SideUp-PJ/",
    repositories: "https://github.com/iym1511/Sunny-SideUp-PJ",
    introduce: "",
    function: "실시간 위치기반 날씨, 5일치 전국 날씨, 날씨에 따른 애니메이션 배경",
    techstack: "React, TypeScript, redux-thunk, style-component",
  },
];
